config/routes.rb
Rails.application.routes.draw do
  # Static
  root 		   'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'contact'	=> 'static_pages#contact'

  # Lair and daemons
  get 'lair'       => 'projects#lair',       as: :lair
  get 'lair/toggle' => 'projects#lair_toggle', as: :lair_toggle
  get 'lair/toggle_daemon/:id' => 'projects#daemon_toggle', as: :daemon_toggle
  get 'lair/start_all_daemons' => 'projects#daemon_start_all',
    as: :daemon_start_all
  get 'lair/stop_all_daemons'  => 'projects#daemon_stop_all',
    as: :daemon_stop_all

  # Login/sessions
  get 'sessions/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup'	=> 'users#new'
  get 'login'	=> 'sessions#new'
  post 'login'	=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Projects
  delete 'projects/:id/delete_ref_dataset' => 'projects#delete_ref_dataset', as: :delete_ref_dataset

  get 'projects/:id/progress' => 'projects#progress', as: :project_progress
  get 'projects/:id/reference_datasets/:dataset' => 'projects#show_dataset',
    as: :reference_dataset
  get 'projects/:id/reference_datasets/:dataset/result/:result/:file' =>
    'projects#reference_dataset_result',
    as: :reference_dataset_result
  get 'projects/:id/search' => 'projects#search',
    as: :project_search
  get 'projects/:project_id/reference_datasets' =>
    'projects#reference_datasets',
    as: :project_reference_datasets
  get 'projects/:project_id/query_datasets' => 'query_datasets#index',
    as: :project_query_datasets
  get 'projects/:id/result/:result/:file' => 'projects#result',
    as: :project_result
  get 'projects/:id/result/:result' => 'projects#result_partial',
    as: :project_result_partial
  get 'projects/:id/ncbi_download' => 'projects#new_ncbi_download',
    as: :project_new_ncbi_download
  post 'projects/:id/ncbi_download' => 'projects#create_ncbi_download',
    as: :project_create_ncbi_download
  get 'projects/:id/new_reference' => 'projects#new_reference',
    as: :project_new_reference
  post 'projects/:id/new_reference' => 'projects#create_reference',
    as: :project_create_reference
  get 'project_discovery' => 'projects#discovery', as: :project_discovery
  get 'project_link' => 'projects#link', as: :project_link
  get 'get_db' => 'projects#get_db', as: :get_db
  get 'launch_get_db/:name/:version' => 'projects#launch_get_db', as: :launch_get_db
  get 'clear_get_db' => 'projects#clear_get_db', as: :clear_get_db

  # Query datasets
  get 'query_datasets/:id/result/:result/:file' => 'query_datasets#result',
    as: :query_dataset_result
  get 'query_datasets/:id/run_mytaxa_scan' => 'query_datasets#run_mytaxa_scan',
    as: :query_dataset_run_mytaxa_scan
  get 'query_datasets/:id/run_distances' => 'query_datasets#run_distances',
    as: :query_dataset_run_distances
  post 'query_datasets/:id/unread' => 'query_datasets#mark_unread',
    as: :query_dataset_mark_unread
  get 'query_datasets/:id/reactivate_dataset' => 'query_datasets#reactivate',
    as: :query_dataset_reactivate

  # Medoid clusters
  get 'medoid_clade/:project_id/:metric/:clade' => 'projects#medoid_clade',
    as: :medoid_clade
  get 'medoid_clade/:project_id/:metric/:clade/as' =>
    'projects#medoid_clade_as',
    as: :medoid_clade_as

  # RDP Classifier
  get 'rdp_classify/:project_id/:ds_name' => 'projects#rdp_classify',
    as: :rdp_classify
  get 'rdp_classify/:project_id/:ds_name/as' => 'projects#rdp_classify_as',
    as: :rdp_classify_as

  # Users
  resources :users
  get 'dashboard' => 'users#dashboard', as: :dashboard
  get 'admin' => 'users#admin', as: :admin
  get 'unactivated_users' => 'users#unactivated_users', as: :unactivated_users
  post 'activate_user' => 'users#activate_user'

  # Full resources
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :destroy, :show]
  resources :query_datasets, only: [:index, :new, :create, :destroy, :show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_default.html.erb
<div class="text-center jumbotron">
  <h1>Welcome to MiGA</h1>
  <h4>The Microbial Genomes Atlas</h4>
  <br/>
  <div class="btn-group" role="group" aria-label="home-actions">
    <% if logged_in? %>
      <% n_proj = Project.where(private: false, official: true).count %>
      <%= link_to pluralize(n_proj, 'project'), projects_path,
            class: 'btn btn-lg btn-secondary', type: 'button' %>
      <% if Settings.user_projects || current_user.admin? %>
        <%= link_to 'Create project', new_project_path,
              class: 'btn btn-lg btn-primary', type: 'button' %>
      <% end %>
    <% else %>
      <%= link_to 'Create user', signup_path,
            class: 'btn btn-lg btn-primary', type: 'button' %>
      <%= link_to 'Log in', login_path,
            class: 'btn btn-lg btn-info', type: 'button' %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About') %>

<div class="container text-center jumbotron">
  <h1>About MiGA Web</h1>
  <h4>Web interface for MiGA,<br/>the Microbial Genomes Atlas</h4>
</div>

<h1>Citation</h1>
<p>If you use MiGA in your research, please cite:</p>
<% MiGA::MiGA.CITATION_ARRAY.each do |ref| %>
  <blockquote class="blockquote"><%= ref %></blockquote>
<% end %>
<br/>

<h1>Behind MiGA</h1>
<p>
  MiGA web is developed and maintained by
  <%= link_to 'Luis M. Rodriguez-R',
        'https://rodriguez-r.com/', target: '_blank' %>.
  The MiGA web codebase is
  <%= link_to 'freely available',
        'http://code.microbial-genomes.org/miga-web', target: '_blank' %>
  under the terms of the terms of the
  <%= link_to 'Artistic License 2.0',
        'http://code.microbial-genomes.org/miga-web/blob/master/LICENSE',
        target: '_blank' %>.
</p>
<p>
  MiGA is the result of a collaboration between the
  <%= link_to 'Kostas Lab',
        'http://enve-omics.gatech.edu/', target: '_blank' %>
  (<%= link_to 'Georgia Institute of Technology',
        'http://www.gatech.edu/', target: '_blank' %>),
  the <%= link_to 'RDP team',
        'http://rdp.cme.msu.edu/', target: '_blank' %>
  (<%= link_to 'Center for Microbial Ecology',
        'http://cme.msu.edu/', target: '_blank' %>,
  <%= link_to 'Michigan State University',
        'https://msu.edu/', target: '_blank' %>), and
  the <%= link_to 'Rodriguez-R lab',
        'https://rodriguez-r.com', target: '_blank' %>
  (<%= link_to 'Aalborg University',
        'https://en.bio.aau.dk/', target: '_blank' %>).
</p><p>
  The MiGA project is funded by the
  <%= link_to 'US National Science Foundation',
        'http://nsf.gov/', target: '_blank' %>
  (<%= link_to 'Award #1356288',
        'http://nsf.gov/awardsearch/showAward?AWD_ID=1356288',
        target: '_blank' %>, and
  <%= link_to 'Award #MCB190042',
        'https://xras.xsede.org/public/requests/31162-XSEDE-MCB190042-1190572',
        target: '_blank' %>).
</p>
<br/>

<h1>Getting MiGA Web</h1>
<p>
  If you want to host your own MiGA web server for your dedicated
  projects, please visit the <%= link_to 'GitHub repository',
  'http://code.microbial-genomes/miga-web', target: '_blank' %> and the
  <%= link_to 'MiGA manual', 'https://manual.microbial-genomes.org/',
  target: '_blank' %>.
</p>
<br/>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class='container text-center jumbotron'>
   <h1>Contact</h1>
   <h4>
     Contact the MiGA developers and community at the
     <a href="https://support.microbial-genomes.org/">Support Page</a>
     <a href="https://groups.google.com/forum/#!forum/miga-users">MiGA Users
   </h4>
</div>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>
<div class='container text-center jumbotron'>
   <h1>Help</h1>
   <h2>
      Nothing to see here yet.
   </h2>
</div>

app/views/static_pages/home.html.erb
<%= render partial: "home_#{ Settings.home_contents }" %>