config/routes.rb
Rails.application.routes.draw do
  # Static
  root 		   'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'contact'	=> 'static_pages#contact'

  # Lair and daemons
  get 'lair'       => 'projects#lair',       as: :lair
  get 'lair/toggle' => 'projects#lair_toggle', as: :lair_toggle
  get 'lair/toggle_daemon/:id' => 'projects#daemon_toggle', as: :daemon_toggle
  get 'lair/start_all_daemons' => 'projects#daemon_start_all',
    as: :daemon_start_all
  get 'lair/stop_all_daemons'  => 'projects#daemon_stop_all',
    as: :daemon_stop_all

  # Login/sessions
  get 'sessions/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup'	=> 'users#new'
  get 'login'	=> 'sessions#new'
  post 'login'	=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Projects
  delete 'projects/:id/delete_ref_dataset' => 'projects#delete_ref_dataset', as: :delete_ref_dataset

  get 'projects/:id/progress' => 'projects#progress', as: :project_progress
  get 'projects/:id/reference_datasets/:dataset' => 'projects#show_dataset',
    as: :reference_dataset
  get 'projects/:id/reference_datasets/:dataset/result/:result/:file' =>
    'projects#reference_dataset_result',
    as: :reference_dataset_result
  get 'projects/:id/search' => 'projects#search',
    as: :project_search
  get 'projects/:project_id/reference_datasets' =>
    'projects#reference_datasets',
    as: :project_reference_datasets
  get 'projects/:project_id/query_datasets' => 'query_datasets#index',
    as: :project_query_datasets
  get 'projects/:id/result/:result/:file' => 'projects#result',
    as: :project_result
  get 'projects/:id/result/:result' => 'projects#result_partial',
    as: :project_result_partial
  get 'projects/:id/ncbi_download' => 'projects#new_ncbi_download',
    as: :project_new_ncbi_download
  post 'projects/:id/ncbi_download' => 'projects#create_ncbi_download',
    as: :project_create_ncbi_download
  get 'projects/:id/new_reference' => 'projects#new_reference',
    as: :project_new_reference
  post 'projects/:id/new_reference' => 'projects#create_reference',
    as: :project_create_reference
  get 'project_discovery' => 'projects#discovery', as: :project_discovery
  get 'project_link' => 'projects#link', as: :project_link
  get 'get_db' => 'projects#get_db', as: :get_db
  get 'launch_get_db/:name/:version' => 'projects#launch_get_db', as: :launch_get_db
  get 'clear_get_db' => 'projects#clear_get_db', as: :clear_get_db

  # Query datasets
  get 'query_datasets/:id/result/:result/:file' => 'query_datasets#result',
    as: :query_dataset_result
  get 'query_datasets/:id/run_mytaxa_scan' => 'query_datasets#run_mytaxa_scan',
    as: :query_dataset_run_mytaxa_scan
  get 'query_datasets/:id/run_distances' => 'query_datasets#run_distances',
    as: :query_dataset_run_distances
  post 'query_datasets/:id/unread' => 'query_datasets#mark_unread',
    as: :query_dataset_mark_unread
  get 'query_datasets/:id/reactivate_dataset' => 'query_datasets#reactivate',
    as: :query_dataset_reactivate

  # Medoid clusters
  get 'medoid_clade/:project_id/:metric/:clade' => 'projects#medoid_clade',
    as: :medoid_clade
  get 'medoid_clade/:project_id/:metric/:clade/as' =>
    'projects#medoid_clade_as',
    as: :medoid_clade_as

  # RDP Classifier
  get 'rdp_classify/:project_id/:ds_name' => 'projects#rdp_classify',
    as: :rdp_classify
  get 'rdp_classify/:project_id/:ds_name/as' => 'projects#rdp_classify_as',
    as: :rdp_classify_as

  # Users
  resources :users
  get 'dashboard' => 'users#dashboard', as: :dashboard
  get 'admin' => 'users#admin', as: :admin
  get 'unactivated_users' => 'users#unactivated_users', as: :unactivated_users
  post 'activate_user' => 'users#activate_user'

  # Full resources
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :destroy, :show]
  resources :query_datasets, only: [:index, :new, :create, :destroy, :show]
end

app/models/user.rb
class User < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_many :projects, dependent: :destroy
  has_many :query_datasets, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
   
  #  Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
   
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  ##
  # Absolute path to the MiGA project including all queries
  # If +dir+ is true, it returns instead the path to the directory containing
  # user-generated projects
  def query_project_path(dir = false)
    File.join(Settings.miga_projects, query_project_path_rel(dir))
  end

  ##
  # Relative path to the MiGA project including all queries
  # (relative to the location of all MiGA projects)
  # If +dir+ is true, it returns instead the path to the directory containing
  # user-generated projects
  def query_project_path_rel(dir = false)
    File.join('user-contributed', "#{id}-q#{dir ? 'P' : 'G'}")
  end

  ##
  # Returns a non-persistent ActiveRecord object of a Project
  # for the user-contributed MiGA (as interface)
  def query_project
    Project.new(path: query_project_path_rel, user: self)
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,
    only: [:index, :edit, :update, :destroy, :show, :dashboard]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,
    only: [:index, :destroy, :unactivated_users, :activate_user, :admin]

  # Show all users
  def index
    @users = User.paginate(page: params[:page])
  end

  # Show user dashboard
  def dashboard
  end

  # Show site admin console
  def admin
  end
  
  def show
     @user = User.find(params[:id])
  end
  
  def new
     @user = User.new
  end

  def create
    par = user_params
    if User.all.empty?
      par[:activated] = true
      par[:activated_at] = Time.zone.now
      par[:admin] = true
    end
    @user = User.new(par)
    if @user.save
      if @user.activated?
        flash[:info] = 'User created, please login.'
      else
        @user.send_activation_email
        flash[:info] = 'Please check your email to activate your account.'
      end
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
	flash[:success] = 'Profile updated'
	redirect_to @user
     else
	render 'edit'
     end
  end

  def destroy
     User.find(params[:id]).destroy
     flash[:success] = 'User deleted'
     redirect_to users_url
  end
  
  # created a unactivatedusers method
  def unactivated_users
    @users = User.where(activated: false).paginate(page: params[:page])
  end

  # admin manually activate user account
  def activate_user
    @user = User.find(params[:id])
    if @user.activate
      flash[:success] = 'activated'
    else
      flash[:danger] = 'Failed to activate user'
    end
    redirect_to unactivated_users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end

  # Before filters

  # Confirms the correct user
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = 'You don\'t have privileges to access this page'
      redirect_to(root_url)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" +
      "?s=#{size}&d=identicon"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar rounded-circle')
  end

  # Indicates if the logged-in user is allowed to perform the action
  def can?(action, object)
    return false unless logged_in?
    return false unless object.is_a?(ApplicationRecord)
    case object
    when Project
      case action
      when :edit
        object.privileged_user?(current_user)
      else
        false
      end
    when QueryDataset
      case action
      when :edit, :delete
        object.privileged_user?(current_user)
      else
        false
      end
    else
      false
    end
  end
end

app/views/users/_user.html.erb
<div class="col-lg-4 col-md-6 col-12 mb-2">
  <div class="card h-100">
    <div class="card-body">
      <%= gravatar_for(user, size: 50) %>
      <%= link_to(user.name, user) %>
      <br/>
      <span class="text-muted">
        <%= fa_icon('history') %>&nbsp;
        <%= time_ago_in_words(user.created_at) %>
      </span>
    </div>
    <% if current_user.admin? %>
      <div class="card-footer">
        <span class="text-muted"><%= user.email %></span><hr/>
          <%= link_to(
                edit_user_path(user), class: 'btn btn-sm btn-primary'
              ) do %>
            <%= fa_icon('user-edit') %> edit
          <% end %>
        <% unless current_user?(user) %>
          <%= link_to(
                user, class: 'btn btn-sm btn-primary',
                method: :delete, data: { confirm: 'You sure?' }
              ) do %>
            <%= fa_icon('user-slash') %> delete
          <% end %>
          <% unless user.activated? %>
            <%= link_to(
                  activate_user_path(id: user.id),
                  class: 'btn btn-sm btn-primary', method: :post
                ) do %>
              <%= fa_icon('user-check') %> activate
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/admin.html.erb
<% provide(:title, 'Admin console') %>
<div class="row dashboard">
  <h1 class="my-4"><%= fa_icon('sliders-h') %> Admin console</h1>
  <div class="col-md-12 list-group">
    <%= list_item(query_datasets_path(all: true)) do %>
      <h4><%= fa_icon('list') %> All query datasets</h4>
      <p>Only admins can see all the query datasets registered in the system</p>
    <% end %>

    <%= list_item(projects_path(user_contributed: true, all: true)) do %>
      <h4><%= fa_icon('list-alt') %> All user-contributed projects</h4>
      <p>Only admins can see all the user-contributed projects in the system</p>
    <% end %>

    <%= list_item(new_project_path) do %>
      <h4><%= fa_icon(:star) %> Create new project</h4>
      <p>As an admin, you can create new projects for different species</p>
    <% end %>

    <%= list_item(lair_path) do %>
      <h4><%= fa_icon(:robot) %> Control and review daemons</h4>
      <p>Administrate and review the status of the daemons for all projects</p>
    <% end %>

    <%= list_item(users_path) do %>
      <h4><%= fa_icon(:users) %> Registered users</h4>
      <p>Only admins can see all the users in the system</p>
    <% end %>
    
    <%= list_item(unactivated_users_path) do %>
      <h4><%= fa_icon('user-check') %> Unactivated users</h4>
      <p>Only admins can activate users in the system</p>
    <% end %>

    <%= list_item(get_db_path) do %>
      <h4><%= fa_icon('cloud-download-alt') %> Download databases</h4>
      <p>Download a pre-indexed database from MiGA Online</p>
    <% end %>

    <%= list_item(project_discovery_path) do %>
      <h4><%= fa_icon(:link) %> Link existing projects</h4>
      <p>Link projects that are already in your data folder</p>
    <% end %>
  </div>
</div>

app/views/users/dashboard.html.erb
<% provide(:title, 'Dashboard') %>

<div class="row dashboard">
  <h1 class="my-4"><%= fa_icon('tachometer-alt') %> Dashboard</h1>
  <div class="col-md-12 list-group">

    <% if Settings.user_create_projects %>
      <%= list_item(new_project_path) do %>
        <h4><%= fa_icon(:star) %> Create new project</h4>
        <p>Create your own project to compare multiple genomes among them</p>
      <% end %>
    <% end %>

    <%= list_item(query_datasets_path) do %>
      <h4><%= fa_icon('list-alt') %> Query datasets</h4>
      <p>You can upload new datasets to any available project</p>
    <% end %>

    <%= list_item(edit_user_path(current_user)) do %>
      <h4><%= fa_icon(:cog) %> Edit profile</h4>
      <p>Change your personal information</p>
    <% end %>
       
    <%= list_item(logout_path, method: :delete) do %>
      <h4><%= fa_icon(:user) %> Log out</h4>
      <p>Au revoir!</p>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
	 <%= render 'shared/error_messages', object: f.object %>

	 <%= form_input do %>
           <%= f.label :name %>
           <%= f.text_field :name, class: 'form-control' %>
         <% end %>

	 <%= form_input do %>
           <%= f.label :email %>
           <%= f.email_field :email, class: 'form-control' %>
         <% end %>

	 <%= form_input do %>
           <%= f.label :password %>
           <%= f.password_field :password, class: 'form-control' %>
         <% end %>

	 <%= form_input do %>
           <%= f.label :password_confirmation, "Confirmation" %>
           <%= f.password_field :password_confirmation, class: 'form-control' %>
         <% end %>

	 <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>

      <hr/>
      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <%=
          link_to(
            'Change avatar',
            'https://gravatar.com/emails',
            class: 'btn btn-secondary', target: '_blank'
          )
        %>
      </div>
   </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1 class="mt-5">All users</h1>
<hr/>
<%= will_paginate(class: 'center-block center') %>

<div class="container user-list">
  <div class="row">
    <%= render(@users) %>
  </div>
</div>

<%= will_paginate(class: 'center-block center') %>
<br/><br/><br/>

app/views/users/new.html.erb
<%= provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
	 <%= render "shared/error_messages", object: f.object %>
	 
	 <div class="alert alert-info my-4">
           <h3>Data privacy</h3>
           We intend to keep your data private, but your data may be subject to
           public disclosure due to security issues, programming error, human
           error, or other reasons. Please keep an up-to-date offline backup of
           your data at all times.
         </div>
         
         <%= form_input do %>
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control" %>
         <% end %>

         <%= form_input do %>
           <%= f.label :email %>
           <%= f.email_field :email, class: "form-control" %>
         <% end %>

         <%= form_input do %>
           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control" %>
         <% end %>

         <%= form_input do %>
           <%= f.label :password_confirmation, "Confirmation" %>
           <%= f.password_field :password_confirmation, class: "form-control" %>
         <% end %>

	 <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
   </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:breadcrumb_1, link_to('Users', users_path)) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user-info row">
      <%= gravatar_for @user %>
      <div class="user-name col-sm-6">
        <h1><%= @user.name %></h1>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%
      {
        'Name' => @user.name,
        'E-mail' => @user.email,
        'Query datasets' => @user.query_datasets.size,
        'Private projects' => @user.projects.where(private: true).size
      }.each do |k, v|
    %>
      <div class="card">
        <div class="card-header"><%= k %></div>
        <div class="card-body"><%= v %></div>
      </div>
      <br/>
    <% end %>
  </div>
</div>

app/views/users/unactivated_users.html.erb
<% provide(:title, 'Users not yet activated') %>
<h1 class="mt-5">Users not yet activated</h1>
<hr/>

<%= will_paginate(class: 'center-block center') %>

<div class="container user-list">
  <div class="row">
    <% @users.each do |user| %>
      <%= render(user) %>
    <% end %>
  </div>
</div>

<%= will_paginate(class: 'center-block center') %>
<br/><br/><br/>