config/routes.rb
Rails.application.routes.draw do
  # Static
  root 		   'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'contact'	=> 'static_pages#contact'

  # Lair and daemons
  get 'lair'       => 'projects#lair',       as: :lair
  get 'lair/toggle' => 'projects#lair_toggle', as: :lair_toggle
  get 'lair/toggle_daemon/:id' => 'projects#daemon_toggle', as: :daemon_toggle
  get 'lair/start_all_daemons' => 'projects#daemon_start_all',
    as: :daemon_start_all
  get 'lair/stop_all_daemons'  => 'projects#daemon_stop_all',
    as: :daemon_stop_all

  # Login/sessions
  get 'sessions/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup'	=> 'users#new'
  get 'login'	=> 'sessions#new'
  post 'login'	=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Projects
  delete 'projects/:id/delete_ref_dataset' => 'projects#delete_ref_dataset', as: :delete_ref_dataset

  get 'projects/:id/progress' => 'projects#progress', as: :project_progress
  get 'projects/:id/reference_datasets/:dataset' => 'projects#show_dataset',
    as: :reference_dataset
  get 'projects/:id/reference_datasets/:dataset/result/:result/:file' =>
    'projects#reference_dataset_result',
    as: :reference_dataset_result
  get 'projects/:id/search' => 'projects#search',
    as: :project_search
  get 'projects/:project_id/reference_datasets' =>
    'projects#reference_datasets',
    as: :project_reference_datasets
  get 'projects/:project_id/query_datasets' => 'query_datasets#index',
    as: :project_query_datasets
  get 'projects/:id/result/:result/:file' => 'projects#result',
    as: :project_result
  get 'projects/:id/result/:result' => 'projects#result_partial',
    as: :project_result_partial
  get 'projects/:id/ncbi_download' => 'projects#new_ncbi_download',
    as: :project_new_ncbi_download
  post 'projects/:id/ncbi_download' => 'projects#create_ncbi_download',
    as: :project_create_ncbi_download
  get 'projects/:id/new_reference' => 'projects#new_reference',
    as: :project_new_reference
  post 'projects/:id/new_reference' => 'projects#create_reference',
    as: :project_create_reference
  get 'project_discovery' => 'projects#discovery', as: :project_discovery
  get 'project_link' => 'projects#link', as: :project_link
  get 'get_db' => 'projects#get_db', as: :get_db
  get 'launch_get_db/:name/:version' => 'projects#launch_get_db', as: :launch_get_db
  get 'clear_get_db' => 'projects#clear_get_db', as: :clear_get_db

  # Query datasets
  get 'query_datasets/:id/result/:result/:file' => 'query_datasets#result',
    as: :query_dataset_result
  get 'query_datasets/:id/run_mytaxa_scan' => 'query_datasets#run_mytaxa_scan',
    as: :query_dataset_run_mytaxa_scan
  get 'query_datasets/:id/run_distances' => 'query_datasets#run_distances',
    as: :query_dataset_run_distances
  post 'query_datasets/:id/unread' => 'query_datasets#mark_unread',
    as: :query_dataset_mark_unread
  get 'query_datasets/:id/reactivate_dataset' => 'query_datasets#reactivate',
    as: :query_dataset_reactivate

  # Medoid clusters
  get 'medoid_clade/:project_id/:metric/:clade' => 'projects#medoid_clade',
    as: :medoid_clade
  get 'medoid_clade/:project_id/:metric/:clade/as' =>
    'projects#medoid_clade_as',
    as: :medoid_clade_as

  # RDP Classifier
  get 'rdp_classify/:project_id/:ds_name' => 'projects#rdp_classify',
    as: :rdp_classify
  get 'rdp_classify/:project_id/:ds_name/as' => 'projects#rdp_classify_as',
    as: :rdp_classify_as

  # Users
  resources :users
  get 'dashboard' => 'users#dashboard', as: :dashboard
  get 'admin' => 'users#admin', as: :admin
  get 'unactivated_users' => 'users#unactivated_users', as: :unactivated_users
  post 'activate_user' => 'users#activate_user'

  # Full resources
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :destroy, :show]
  resources :query_datasets, only: [:index, :new, :create, :destroy, :show]
end

app/controllers/projects_controller.rb
require 'miga'
require 'miga/daemon'

class ProjectsController < ApplicationController
  before_action :set_project,
    only: [:destroy, :show, :search, :reference_datasets,
      :medoid_clade, :medoid_clade_as,
      :rdp_classify, :rdp_classify_as,
      :new_ncbi_download, :create_ncbi_download,
      :show_dataset, :result, :result_partial, :reference_dataset_result,
      :daemon_toggle, :new_reference, :create_reference, :progress,
      :delete_ref_dataset]
  before_action :logged_in_user, only: [:result]
  before_action :admin_user,
    only: [:lair, :lair_toggle, :daemon_toggle,
      :daemon_start_all, :daemon_stop_all, :daemon_action_all,
      :discovery, :link, :get_db, :launch_get_db, :clear_get_db]
  if Settings.user_projects
    # Servers with user-owned projects
    before_action(
      Settings.user_create_projects ? :logged_in_user : :admin_user,
      only: [:new, :create]
    )
    before_action :correct_user_or_admin,
      only: [:destroy, :new_ncbi_download, :create_ncbi_download,
        :new_reference, :create_reference, :progress, :delete_ref_dataset]
  else
    # Servers without user-owned projects
    before_action :admin_user,
      only: [:new, :create, :destroy, :new_ncbi_download, :create_ncbi_download,
        :new_reference, :create_reference, :progress, :delete_ref_dataset]
  end

  # Initiate (paginated) list of projects.
  def index
    @selection = :public
    if params[:private]
      @selection = :private
      @projects = Project.where(private: true, user: current_user)
            .paginate(page: params[:page])
    elsif params[:user_contributed]
      sel = { official: false }
      sel[:private] = false unless current_user.admin? && params[:all]
      @selection = :'user-contributed'
      @projects = Project.where(sel)
      @projects = @projects.reorder(created_at: :asc) if sel[:private] == false
      @projects = @projects.paginate(page: params[:page])
    elsif params[:type]
      @selection = params[:type].to_sym
      @projects = Project.where(private: false, official: true)
            .select { |i| !i.miga.nil? and i.miga.type.to_s == params[:type] }
            .paginate(page: params[:page])
    else
      @projects = Project.where(private: false, official: true)
            .paginate(page: params[:page])
    end
  end
  
  # GET /project/new
  # Create an empty abstract project
  def new
    @project = Project.new
    @refdb = Project.where(reference: true)
  end

  # GET /project/1
  # Loads a given project
  def show
  end

  # Queries reference datasets in the project
  def search
    # Query
    @q       = params[:q]
    @query   = @q.split(/\s(?=(?:[^"]|"[^"]*")*$)/).map do |i|
      (i =~ /^(?:([A-Za-z_]+):)?"?(.*?)"?$/) ? [$2, $1] : [i, nil]
    end
    # Results
    return if (m = @project.miga).nil? or
              (r = m.result(:project_stats)).nil? or
              (db_file = r.file_path(:metadata_index)).nil?
    db = SQLite3::Database.new db_file
    @results = nil
    @query.each do |q|
      q[0] = q[0].downcase.gsub(/[^A-Za-z0-9\-]+/, " ")
      res = db.execute("select distinct(name) from metadata " +
              "where value like ? #{"and field=?" unless q[1].nil?}",
              ["% #{q[0]} %"] + (q[1].nil? ? [] : [q[1]])).flatten
      @results.nil? ? @results=res :
        @results.select!{ |i| res.include? i }
    end
    reference_datasets
  end
  
  # Loads (paginated) list of reference datasets in a project.
  def reference_datasets
    if @results.nil?
      @ref_datasets = @project.ref_datasets
    else
      @ref_datasets = @results
    end
    cur_page = (params[:page] || 1).to_i
    per_page = (params[:per_page] || 10).to_i
    @datasets = WillPaginate::Collection.create(
                        cur_page, per_page, @ref_datasets.size) do |pager|
      start = (cur_page - 1) * per_page
      pager.replace(@ref_datasets[start, per_page])
    end
  end
  
  # Loads a medoid clade for in-page display.
  def medoid_clade
    redirect_to root_url if @project.miga.nil?
    @metric = params[:metric].to_sym
    @result = @project.miga.add_result(
      @metric==:AAI ? :clade_finding : :subclades, false)
    @clade = params[:clade]
    @clade_name = "#{@metric} clade #{@clade}"
    @clade_miga = @clade.split('-').
      map{ |i| "miga-project.sc-#{i}" }.join('/')
  end
  
  # Loads a medoid clade for asynchronous display.
  def medoid_clade_as
    medoid_clade
    render partial: 'medoid_clade',
      locals: { project: @project, result: @result, metric: @metric,
        target: @clade, root: File.expand_path(@clade_miga, @result.dir),
	root_name: @clade },
      layout: false
  end

  # Loads an RDP classification for in-page display.
  def rdp_classify
    redirect_to root_url if @project.miga.nil?
    @ds_name = params[:ds_name]
    @result = @project.rdp_classify(@ds_name)
  end

  # Loads an RDP classification for asynchronous display.
  def rdp_classify_as
    rdp_classify
    render partial: 'rdp_classify',
      locals: { project: @project, ds_name: @ds_name, result: @result },
      layout: false
  end

  # Loads a given dataset in a project.
  def show_dataset
    @dataset_miga = @project.miga.dataset(params[:dataset])
    redirect_to root_url if @dataset_miga.nil?
  end

  # Create project
  def create
    @user = User.find_by(id: params[:user_id])
    par = project_params
    par[:official] = false unless @user.admin?
    @project = @user.projects.create(par)
    if @project.save && !@project.miga.nil?
      [:name, :description, :comments, :type,
            :ani_p, :aai_p, :haai_p].each do |k|
        @project.miga.metadata[k] = params[k] unless
          params[k].nil? || params[k].empty?
      end
      if params[:reference_db]
        if Settings.miga_exec_projects
          @project.miga.metadata[:ref_project] =
            File.join(Settings.miga_exec_projects, params[:reference_db])
        else
          ref = Project.find_by(path: params[:reference_db])
          ref_path = ref.miga.path if ref && ref.miga
          @project.miga.metadata[:ref_project] = ref_path
        end
      end
      @project.miga.save
      flash[:success] = 'Project created'
      redirect_to @project
    else
      render 'new'
    end
  end
  
  # Destroys project
  def destroy
    FileUtils.rm_rf @project.miga.path
    @project.destroy
    flash[:success] = 'Project deleted'
    redirect_to root_url
  end
  
  # Loads a result of a project
  def result
    if @project && @project.miga &&
          (result = @project.miga.result(params[:result])) &&
          (file = result.data[:files][params[:file].to_sym])
      send_result(file, result)
    else
      head :ok, content_type: 'text/html'
    end
  end

  # Displays the result as a partial for asynchronous loading
  def result_partial
    if params[:q_ds].nil?
      obj = @project
      proj = obj
      unless params[:r_ds].nil?
        obj = obj.miga.dataset(params[:r_ds])
        obj_miga = obj
      end
    else
      obj = QueryDataset.find(params[:q_ds])
    end
    obj_miga ||= obj.miga
    res = obj_miga.result(params[:result])
    render partial: 'shared/result',
      locals: { res: res, key: params[:result].to_sym, obj: obj, proj: proj },
      layout: false
  #rescue
  #  head :ok, content_type: 'text/html'
  end

  # Loads a result from a reference dataset in a project
  def reference_dataset_result
    if p = @project and m = p.miga
      if ds = m.dataset(params[:dataset]) and res = ds.result(params[:result])
        if file = res.data[:files][params[:file].to_sym]
          send_result(file, res)
          return
        end
      end
    end
    render nothing: true, status: 200, content_type: 'text/html'
  end

  # Initiates project for NCBI download
  def new_ncbi_download
    show
  end
  
  # Launches an NCBI download in the background
  def create_ncbi_download
    if params[:species].nil? || params[:species].empty?
      flash[:danger] = 'Species name cannot be empty'
      redirect_to project_new_ncbi_download_url(@project)
      return
    end

    s = %i[complete chromosome scaffold contig].select { |i| params[i] }
    if @project.ncbi_download!(params[:species], s.compact)
      flash[:success] = 'Downloading reference genomes in the background...'
      redirect_to @project
    else
      render 'new_ncbi_download'
    end
  end

  # List remote databases to download
  def get_db
    manif = Project.miga_online_manif
    @downloadable = manif[:databases].map do |name, i|
      local = Project.find_by(path: name)
      local_v = (local.miga.metadata[:release] || 'unknown') if local && local.miga
      latest = i[:versions][i[:latest].to_sym]
      file = File.join(Settings.miga_projects, latest[:path])
      downloading = File.size(file) * 100 / latest[:size] if File.exist?(file)
      i.merge(name: name, local: local_v, downloading: downloading)
    end
  end

  # Download or update the database in the background
  def launch_get_db
    name = params.require(:name)
    version = params.require(:version)
    arch = File.join(Settings.miga_projects, "#{name}_#{version}.tar.gz")
    FileUtils.touch(arch)
    GetDbJob.perform_later(name, version, current_user)
    flash[:success] = 'Downloading database in the background'
    redirect_to(get_db_path)
  end

  # Clear a failed download
  def clear_get_db
    name = params.require(:name)
    version = params.require(:version)
    arch = File.join(Settings.miga_projects, "#{name}_#{version}.tar.gz")
    File.unlink(arch) if File.exist?(arch)
    flash[:success] = 'Temporary archive successfully removed'
    redirect_to(get_db_path)
  end

  # Admin daemons
  def lair
    require 'miga/lair'

    @projects = Project.all
    @lair = MiGA::Lair.new(Settings.miga_projects)
  end

  def lair_toggle
    require 'miga/lair'

    lair = MiGA::Lair.new(Settings.miga_projects)
    lair_or_daemon_toggle(lair, 'daemon controller')
    redirect_to(lair_url)
  end

  def daemon_toggle

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_code(project)
    link_to(
      project.code, project,
      class: 'project-code rounded',
      style: "background: #{project.code_color};",
      title: project.path.unmiga_name
    )
  end

  def estimated_wait_time(project_id)
    @estimated_wait_time_last_check ||= []
    @estimated_wait_time ||= []
    if @estimated_wait_time_last_check[project_id].nil? or
          @estimated_wait_time_last_check[project_id] < 48.hours.ago
      p = Project.find(project_id)
      ds = p.query_datasets.where(complete: true).first(5)
      t = 0.0
      ds.each do |d|
        d.miga.each_result do |k,r|
          t += (r.running_time||0) unless k==:mytaxa_scan
        end
      end
      @estimated_wait_time_last_check[project_id] = DateTime.now
      @estimated_wait_time[project_id] = t/ds.size/60
    end
    [ @estimated_wait_time[project_id],
          @estimated_wait_time_last_check[project_id] ]
  end

  def miga_dataset_type(miga_dataset)
    md = miga_dataset&.metadata || {}
    md[:is_type] ?
        content_tag(:sup, md[:seqcode] ? 'Ts' : 'T',
          title: md[:type_rel] || 'Type strain',
          style: 'font-weight:bold;') :
      md[:is_ref_type] ?
        content_tag(:sup, 'R',
          title: md[:type_rel] || 'Reference material',
          style: 'font-weight:bold;') : nil
  end

  def link_to_reference_dataset(project, dataset_name)
    pm = project.miga if project
    ds_miga = pm.dataset(dataset_name) if pm
    if ds_miga.nil?
      @_del_reference_dataset ||= []
      @_del_reference_dataset << [project, dataset_name]
      content_tag(:del, dataset_name, title: 'Reference dataset removed')
    else
      md = ds_miga.metadata
      link_to(reference_dataset_path(project.id, dataset_name)) do
        content_tag(:span, dataset_name.unmiga_name,
          style: 'display:inline;') + (
            md[:strain] ? (
              content_tag(:span, ' (') + md[:strain] +
                miga_dataset_type(ds_miga) + content_tag(:span, ')')
            ) : miga_dataset_type(ds_miga)
          )
      end
    end
  end

  def _del_reference_dataset
    @_del_reference_dataset ||= []
    @_del_reference_dataset
  end
  def _empty_del_reference_dataset!
    @_del_reference_dataset = []
  end
end

app/views/projects/_dataset_side.html.erb
<%= accordion('dataset-metadata') do |accordion| %>
  <% unless dataset.metadata[:tax].nil? %>
    <%= accordion_card(accordion, 'taxonomy', 'Taxonomy') do %>
      <ul class='panel-body taxonomy'>
      <% tax = dataset.metadata[:tax].sorted_ranks.map{ |r| r.join(": ")} %>
      <% tax.each do |r| %>
        <% r = r.split(": ") %>
        <li>
          <span class=text-muted><%= r[0] %>:</span>
          <% if r[1] =~ /^(Candidatus) (.*)/ %>
            <i><%= $1 %></i> <%= $2 %>
          <% else %>
            <i><%= r[1] %></i>
          <% end %>
        </li>
      <% end %>
      </ul>
    <% end %>
  <% end %>

  <% dataset.metadata.each do |k,v| %>
    <% next if [:type, :ref, :created, :updated, :user, :tax,
          :quality, :is_type, :is_ref_type, :type_rel, :status].include? k %>
    <% next if k.to_s[0] == '_' %>
    <% k_str = k.to_s.unmiga_name.capitalize %>
    <%
      ext_links = {
        ncbi_tax_id: ['NCBI TaxID',
              'http://www.uniprot.org/taxonomy/%s', '%s'],
        ncbi_nuccore: ['NCBI Nucleotide',
              'https://www.ncbi.nlm.nih.gov/nuccore/%s', '%s'],
        ncbi_asm: ['NCBI Assembly',
              'https://www.ncbi.nlm.nih.gov/assembly/%s', '%s'],
        ebi_ena: ['EBI ENA',
              'https://www.ebi.ac.uk/ena/data/view/%s', '%s'],
        ebi_embl: ['EBI EMBL',
              'https://www.ebi.ac.uk/embl/data/view/%s', '%s'],
        web_assembly: ['Download',
              '%s', 'Assembly'],
        web_assembly_gz: ['Download',
              '%s', 'Assembly (gz)'],
        dprotologue: ['Digital Protologue Database',
              'http://imedea.uib-csic.es/dprotologue/getPdfTX.php?taxonumber=%s', '%s']
      }
      case k
      when :comments
        if /(.*)Assembly: (\S+)(.*)/.match(v)
          v = "#{$1}<a href='https://www.ncbi.nlm.nih.gov/assembly/#{$2}/' " +
                "target=_blank>Assembly: #{$2}</a>#{$3}"
        end
      when *ext_links.keys
        k_str = ext_links[k][0]
        v = v.split(/[,;]/).map do |i|
          "<a href='#{ext_links[k][1] % i}' target=_blank>#{ext_links[k][2] % i}</a>"
        end.join(", ")
      when :see_also
        k_str = 'See also'
        v = v.split(/[,;]/).map do |i|
          l = i.split(/:/, 2)
          "<a href='#{l[1]}' target=_blank>#{l[0]}</a>"
        end.join(', ')
      end
    %>
    <%= accordion_card(accordion, k, k_str) do %>
      <%= display_data(v, true) %>
    <% end %>
  <% end %>
  
  <% method = project.miga.is_clade? ? :subclades : :clade_finding %>
  <% unless (clade_r = dataset.project.result(method)).nil? %>
    <% unless (clade_f = clade_r.file_path(:class_table)).nil? %>
      <% File.open(clade_f, 'r') do |fh| %>
        <% clade = (fh.each_line.
              grep(/^#{dataset.name}\t/).first || '').chomp.split("\t") %>
        <% unless clade.nil? or clade.empty? %>
          <% metric = project.miga.is_clade? ? 'ANI' : 'AAI' %>
          <%= accordion_card(accordion, 'classification',
                "#{metric} classification" ) do %>
            <ul class='taxonomy'>
            <% cmp = "" %>
            <% clade.each_index do |i| %>
              <% next if i == 0 or clade[i] == '0' %>
              <% cmp += "#{clade[i]}" %>
              <li>
                <span class=text-muted><%= i %>:</span>
                <%= link_to cmp, medoid_clade_url(project.id, metric, cmp) %>
              </li>
              <% cmp += "-" %>
            <% end %>
            </ul>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <% unless method == :subclades or
          (ani_clade_f = clade_r.file_path(:clades_ani95)).nil? %>
      <% unless (ani_clade = File.foreach(ani_clade_f).
            map  { |i| i.chomp.split(',') }.
            find { |i| i.include? dataset.name }).nil? %>
        <%= accordion_card(accordion, 'ani_clade', 'ANI clade') do %>
          <ul style='list-style: circle;'>
            <% ani_clade.each do |i| %>
              <li><%= link_to_reference_dataset(project, i) %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end # Accordion %>

app/views/projects/_medoid_clade.html.erb
<% root_name += "-" unless root_name == "" %>
<% medoids_file = File.expand_path("miga-project.medoids", root) %>
<% classif_file = File.expand_path("../miga-project.classif", root) %>
<% if File.exist? medoids_file %>
  <ul class="medoid-tree list-group">
  <% File.open(medoids_file, "r") do |f| %>
    <% i = 0 %>
    <% f.each_line do |ln| %>
      <% i += 1 %>
      <% sc_name = "#{root_name}#{i}" %>
      <% ln.chomp! %>
      <li class="list-group-item">
        <%= link_to(medoid_clade_url(project.id, metric, sc_name),
              :id => "link-#{metric}-#{root_name}#{i}",
              :remote => true, :"data-target" => "##{metric}-#{sc_name}",
              :"data-url" => medoid_clade_as_url(project.id,
                  metric, sc_name)) do %>
          <i class='glyphicon glyphicon-tree-deciduous'> </i>
          <%= metric %> clade <%= sc_name %>
        <% end %>
        <script>
          $('#link-<%= "#{metric}-#{sc_name}" %>').click(function(event) {
            var t = $($(this).data("target"));
            if(t.data('loaded')){
              t.toggle();
            }else{
              t.html("loading...");
	      t.load($(this).data('url'));
              t.data('loaded', true);
            }
            event.preventDefault();
            event.stopPropagation();
          });
        </script>
	<span class="medoid">
	  <%= link_to(
	    "<i class='permalink glyphicon glyphicon-link'> </i>".html_safe,
	    medoid_clade_url(project.id, metric, "#{root_name}#{i}"),
	    title: "permalink") %>
	  medoid: <%= link_to ln.unmiga_name,
	    reference_dataset_url(project.id, ln) %>
	</span>
        <div id="<%= "#{metric}-#{root_name}#{i}" %>">
	  <% if target =~ /^#{root_name}#{i}(-.+)?$/ %>
	    <script>
              $('#<%= "#{metric}-#{root_name}#{i}" %>').data('loaded', true);
            </script>
            <%= render partial: "medoid_clade",
	      locals: { project: project, result: result, metric: metric,
              target: target, root: "#{root}/miga-project.sc-#{i}",
              root_name: "#{root_name}#{i}" } %>
	  <% end %>
	</div>
      </li>
    <% end %>
  <% end %>
  </ul>
<% elsif File.exist? classif_file %>
  <% lowest_class = root_name.split("-").last %>
  <% datasets = [] %>
  <% id = [] %>
  <% File.open(classif_file, "r") do |f| %>
    <% f.each_line do |ln| %>
      <% r = ln.chomp.split(/\t/) %>
      <% next unless r[1] == lowest_class %>
      <% datasets << r[0] %>
      <% id << r[3].to_f.round(2).to_s %>
    <% end %>
  <% end %>
  <div class="datasets list-group-item">
    <b><%= pluralize(datasets.size, "dataset") %>:</b>
    <%= datasets.map do |d| %>
      <% link_to(d.unmiga_name, reference_dataset_url(project.id, d)) +
        " <span class=medoid>(#{metric}: #{id.shift}%)</span>".html_safe %>
    <% end.to_sentence.html_safe %>
  </div>
<% end %>

app/views/projects/_search_bar.html.erb
<%= form_tag project_search_path, method: 'get' do %>
  <div class="input-group">
    <%= text_field_tag('q', @q,
                       placeholder: 'Search datasets', class: 'form-control') %>
    <div class=input-group-append>
      <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
        <%= fa_icon(:search) %>
      <% end %>
    </div>
  </div>
<% end  %>

app/views/projects/new_ncbi_download.html.erb
<% provide(:title, 'Download NCBI genomes') %>
<% provide(:breadcrumb_1, link_to('Projects', projects_path)) %>
<% provide(:breadcrumb_2, link_to(truncate(@project.path_name, length: 15), @project)) %>
<% content_for :head do %>
  <script type="text/javascript">
    $(function() {
      $('#on-click-loading').click(function() {
        $('#loading-message').modal('show');
      })
    });
  </script>
<% end %>
<h1>Download available NCBI genomes</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="projects"><%= render @project %></div>
    <hr/>
    <%= form_for(@project, url: project_create_ncbi_download_path(@project), method: :post) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :project_id, @project.id %>

      <%= label_tag :species %>
      <%= text_field_tag :species, @project.path_name.unmiga_name, class: "form-control" %>
      <br/>
       
      <%= label_tag :complete, class: 'checkbox' do %>
        <span><%= check_box_tag :complete, 1, true %> Include complete genomes</span>
      <% end %>

      <%= label_tag :chromosome, class: 'checkbox' do %>
        <span><%= check_box_tag :chromosome, 1, true %> Include genomes with complete chromosomes</span>
      <% end %>
      
      <%= label_tag :scaffold, class: 'checkbox' do %>
        <span><%= check_box_tag :scaffold, 1, false %> Include draft genomes at scaffold level</span>
      <% end %>

      <%= label_tag :contig, class: 'checkbox' do %>
        <span><%= check_box_tag :contig, 1, false %> Include draft genomes at contig level</span>
      <% end %>

      <br/>

      <%= f.submit "Start download", class: "btn btn-primary", id: "on-click-loading" %>
    <% end %>
  </div>
  <div class="modal fade" id="loading-message" tabindex="-1" role="dialog" data-keyboard=false>
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="jumbotron text-center">
            <h1>Please do not close or reload this page until the action is complete...</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/search.html.erb
<% provide(:title, @project.path_name) %>
<% provide(:breadcrumb_1, link_to("Projects", projects_path)) %>
<div class="row">
  <aside class="col-md-4">
    <%= render partial: "shared/menu_datasets",
      locals: { project: @project,
      ds_counts: @project.dataset_counts(current_user),
      ref_datasets: false, qry_datasets: false } %>
  </aside>
  <div class="col-md-8">
    <br/>
    <%= render partial: 'projects/search_bar' %>
    <p class=text-right>
      <%= pluralize(@results.size, 'result') %>
    </p>
    <% if @results.any? %>
      <%= will_paginate @datasets, class: "center-block center" %>
      <div class='dataset-list'>
        <% @datasets.each do |dataset| %>
          <%= render partial: 'datasets/dataset',
            object: @project.miga.dataset(dataset),
            locals: { project: @project } %>
        <% end %>
      </div>
      <%= will_paginate @datasets, class: "center-block center" %>
    <% end %>
  </div>
</div>