config/routes.rb
Rails.application.routes.draw do
  # Static
  root 		   'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'contact'	=> 'static_pages#contact'

  # Lair and daemons
  get 'lair'       => 'projects#lair',       as: :lair
  get 'lair/toggle' => 'projects#lair_toggle', as: :lair_toggle
  get 'lair/toggle_daemon/:id' => 'projects#daemon_toggle', as: :daemon_toggle
  get 'lair/start_all_daemons' => 'projects#daemon_start_all',
    as: :daemon_start_all
  get 'lair/stop_all_daemons'  => 'projects#daemon_stop_all',
    as: :daemon_stop_all

  # Login/sessions
  get 'sessions/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'signup'	=> 'users#new'
  get 'login'	=> 'sessions#new'
  post 'login'	=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Projects
  delete 'projects/:id/delete_ref_dataset' => 'projects#delete_ref_dataset', as: :delete_ref_dataset

  get 'projects/:id/progress' => 'projects#progress', as: :project_progress
  get 'projects/:id/reference_datasets/:dataset' => 'projects#show_dataset',
    as: :reference_dataset
  get 'projects/:id/reference_datasets/:dataset/result/:result/:file' =>
    'projects#reference_dataset_result',
    as: :reference_dataset_result
  get 'projects/:id/search' => 'projects#search',
    as: :project_search
  get 'projects/:project_id/reference_datasets' =>
    'projects#reference_datasets',
    as: :project_reference_datasets
  get 'projects/:project_id/query_datasets' => 'query_datasets#index',
    as: :project_query_datasets
  get 'projects/:id/result/:result/:file' => 'projects#result',
    as: :project_result
  get 'projects/:id/result/:result' => 'projects#result_partial',
    as: :project_result_partial
  get 'projects/:id/ncbi_download' => 'projects#new_ncbi_download',
    as: :project_new_ncbi_download
  post 'projects/:id/ncbi_download' => 'projects#create_ncbi_download',
    as: :project_create_ncbi_download
  get 'projects/:id/new_reference' => 'projects#new_reference',
    as: :project_new_reference
  post 'projects/:id/new_reference' => 'projects#create_reference',
    as: :project_create_reference
  get 'project_discovery' => 'projects#discovery', as: :project_discovery
  get 'project_link' => 'projects#link', as: :project_link
  get 'get_db' => 'projects#get_db', as: :get_db
  get 'launch_get_db/:name/:version' => 'projects#launch_get_db', as: :launch_get_db
  get 'clear_get_db' => 'projects#clear_get_db', as: :clear_get_db

  # Query datasets
  get 'query_datasets/:id/result/:result/:file' => 'query_datasets#result',
    as: :query_dataset_result
  get 'query_datasets/:id/run_mytaxa_scan' => 'query_datasets#run_mytaxa_scan',
    as: :query_dataset_run_mytaxa_scan
  get 'query_datasets/:id/run_distances' => 'query_datasets#run_distances',
    as: :query_dataset_run_distances
  post 'query_datasets/:id/unread' => 'query_datasets#mark_unread',
    as: :query_dataset_mark_unread
  get 'query_datasets/:id/reactivate_dataset' => 'query_datasets#reactivate',
    as: :query_dataset_reactivate

  # Medoid clusters
  get 'medoid_clade/:project_id/:metric/:clade' => 'projects#medoid_clade',
    as: :medoid_clade
  get 'medoid_clade/:project_id/:metric/:clade/as' =>
    'projects#medoid_clade_as',
    as: :medoid_clade_as

  # RDP Classifier
  get 'rdp_classify/:project_id/:ds_name' => 'projects#rdp_classify',
    as: :rdp_classify
  get 'rdp_classify/:project_id/:ds_name/as' => 'projects#rdp_classify_as',
    as: :rdp_classify_as

  # Users
  resources :users
  get 'dashboard' => 'users#dashboard', as: :dashboard
  get 'admin' => 'users#admin', as: :admin
  get 'unactivated_users' => 'users#unactivated_users', as: :unactivated_users
  post 'activate_user' => 'users#activate_user'

  # Full resources
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :destroy, :show]
  resources :query_datasets, only: [:index, :new, :create, :destroy, :show]
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid">
  <div class="row">
    <div class="col-sm-6 text-center">
      <nav class="nav flex-column">
        <h5>MiGA Online</h5>
        <%=
          link_to(
            'Help', 'https://help.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%= link_to('About', about_path, class: 'nav-link') %>
        <%=
          link_to(
            'Support',
            'http://support.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <hr/>
        <h5>More MiGA</h5>
        <%=
          link_to(
            'MiGA@XSEDE',
            'https://xsede.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'Container',
            'http://container.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'Base code',
            'http://code.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'News',
            'http://miga.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'Roadmap',
            'http://roadmap.microbial-genomes.org/',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
      </nav>
    </div>
    <div class="col-sm-6 text-center">
      <nav class="nav flex-column">
        <h5>Engine</h5>
        <%=
          link_to(
            'MiGA Web 2.0rc2',
            'http://code.microbial-genomes.org/miga-web',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'http://code.microbial-genomes.org/miga',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          ) do
        %>
          <%= image_tag('MiGA.png', alt: 'MiGA logo', style: 'margin-top: -1em;') %>
          <br/> <%= MiGA::MiGA.LONG_VERSION.sub(/MiGA (.*) - .*/, '\1') %>
        <% end %>
        <hr/>
        <h5>Funded by</h5>
        <%=
          link_to(
            'US NSF #1356288',
            'http://nsf.gov/awardsearch/showAward?AWD_ID=1356288',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
        <%=
          link_to(
            'US NSF #MCB190042',
            'https://xras.xsede.org/public/requests/31162-XSEDE-MCB190042-1190572',
            target: '_blank', rel: 'noopener', class: 'nav-link'
          )
        %>
      </div>

    </div>
  </div>
</footer>
<div class='container p-5'>
  <div class="row text-center rounded" id="footer-collab">
    <div class="col-12">
      <h5>A collaboration between</h5>
      <%=
        link_to(
          image_tag('GT.png', alt: 'Georgia Tech logo'),
          'http://enve-omics.gatech.edu/',
          target: '_blank', rel: 'noopener'
        )
      %>
      <%=
        link_to(
          image_tag('RDP.png', alt: 'RDP logo'),
          'http://rdp.cme.msu.edu/',
          target: '_blank', rel: 'noopener'
        )
      %>
      <%=
        link_to(
          image_tag(
            'LFU.webp', alt: 'University of Innsbruck logo',
            style: 'width: auto; height: 75px;'
          ),
          'https://disc-genomics.uibk.ac.at/',
          target: '_blank', rel: 'noopener'
        )
      %>
      <%=
        link_to(
          image_tag(
            'AAU.png', alt: 'Aalborg University logo',
            style: 'width: auto; height: 50px;',
            class: 'ml-3'
          ),
          'https://en.bio.aau.dk/',
          target: '_blank', rel: 'noopener'
        )
      %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow d-flex">
  <div class="mx-4"></div>
  <%= link_to('MiGA', root_url, id: 'logo', class: 'nav-link') %>
  <ul class="nav justify-content-end flex-fill">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
          role="button" aria-haspopup="true" aria-expanded="false">Projects</a>
      <div class="dropdown-menu dropdown-menu-right">
        <%
          menu = [
            ['Public', :globe, projects_path],
            ['User-contributed', :user, projects_path(user_contributed: true)],
            ['Clade', :tree, projects_path(type: :clade)]
          ]
          if logged_in? && Settings.user_projects
            menu.unshift ['Private', :lock, projects_path(private: true)]
          end
        %>
        <% menu.each do |item| %>
          <%= link_to(item[2], class: 'dropdown-item') do %>
            <%= fa_icon item[1] %> <%= item[0] %>
          <% end %>
        <% end %>
      </div>
    </li>

    <% if logged_in? %>
      <% new_ds = QueryDataset.complete_new_by_user(current_user).count %>
      <% if new_ds > 0 %>
        <li class="nav-item">
          <%= link_to(query_datasets_path(complete_new: true)) do %>
            <span class="badge badge-info mt-2"><%= new_ds %> ready</span>
          <% end %>
        </li>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
            role="button" aria-haspopup="true" aria-expanded="false">
          <%= gravatar_for(current_user, size:20) %>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to(dashboard_url, class: 'dropdown-item') do %>
            <%= fa_icon 'tachometer-alt' %> Dashboard
          <% end %>
          <% if current_user.admin? %>
            <%= link_to(admin_url, class: 'dropdown-item') do %>
              <%= fa_icon('sliders-h') %> Admin console
            <% end %>
          <% end %>
          <%= link_to(query_datasets_path, class: 'dropdown-item') do %>
            <%= fa_icon('list-alt') %> Query datasets
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to(logout_path, method: :delete, class: 'dropdown-item') do %>
            <%= fa_icon :user %> Log out
          <% end %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to('Log in', login_path, class: 'nav-link') %>
      </li>
    <% end %>
  </ul>
  <div class="mx-4"></div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
   </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=en>
<head>
  <% unless Settings.google_tracking_id.nil? %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%=
          Settings.google_tracking_id %>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '<%= Settings.google_tracking_id %>');
    </script>
  <% end %>
  <title><%= full_title(yield :title) %></title>
  <%=
    stylesheet_link_tag(
      'application', media: 'all', 'data-turbolinks-track': 'reload'
    )
  %>
  <%= javascript_include_tag('application', 'data-turbolinks-track' => true) %>
  <%=
    javascript_include_tag(
      'https://cdn.plot.ly/plotly-latest.min.js',
      'data-turbolinks-track' => true,
      'async' => true
    )
  %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= render 'layouts/shim' %>
  <%= csrf_meta_tags %>
  <% if Rails.configuration.try(:plausible_server).present? %>
    <script
      defer event-app="miga"
      data-domain="<%= Rails.configuration.plausible_domain %>"
      src="<%= Rails.configuration.plausible_server %>/js/script.pageview-props.js"
    ></script>
  <% end %>

  <%= yield :head %>
</head>
<body>
  <a class="skip-nav-link" href="#main-content">skip navigation</a>
  <%= render 'layouts/header' %>
  <main role="main" id="main-content">
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <div class="push"></div>
  </main>
  <%= info_msg_content %>
  <%= render 'layouts/footer' %>
  <%# debug(params) if Rails.env.development? %>
</body>
</html>